version: "3.0"

services:
  mongodb:
    image: "canchesi/gallettabot:mongo-1.0"
    container_name: "mongoGallettaBot"
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: "root"
      MONGO_INITDB_ROOT_PASSWORD: "root"
    volumes:
      - "GallettaBotVolume:/data/db"
    networks:
      - "default"

  gallettaBot:
    image: "canchesi/gallettabot:1.4"
    container_name: "GallettaBot"
    environment:
      TELEGRAM_TOKEN: "5520286465:AAGfEVNeE4g5cdhIMVBKNhhXXZ8AarzYU-U"
      BOTNAME: "GallettaBot"
      MONGO_URL: "claudioanchesi.ddns.net:27017"
      MONGO_USER: "root"
      MONGO_PASS: "root"
      MONGO_EXTRA: "authSource=admin"
      MONGO_PREFIX: "mongodb"
    depends_on:
      - "mongodb"
    networks:
      - "default"

    
volumes:
  GallettaBotVolume:
    
networks:
  default:
