version: "3.0"

services:
  #mongodb:
  #  image: "mongo:latest"
  #  container_name: "mongoGallettaBot"
  #  ports:
  #    - "27017:27017"
  #  environment:
  #    MONGO_INITDB_ROOT_USERNAME: "root"
  #    MONGO_INITDB_ROOT_PASSWORD: "root"
  #  volumes:
  #    - "GallettaBotVolume:/data/db"
  #  networks:
  #    - "default"

  gallettaBot:
    image: "klaus:5000/gallettabot:1.2"
    container_name: "GallettaBot"
    environment:
      MONGO_URL: "gallettabotcluster.olrflfi.mongodb.net"
      MONGO_USER: "galletta"
      MONGO_PASS: "galletta"
      MONGO_EXTRA: "?retryWrites=true&w=majority"
        #depends_on:
        #- "mongodb"
    networks:
      - "default"

    
volumes:
  GallettaBotVolume:
    
networks:
  default:
